version: 1.0
description: "Employee data validation with fields"

inputs:
  employees:
    input_file_path: "employees.json"
    input_file_type: "json"
    hive_table: "employees"
    hive_database: "test_db"

  department:
    input_file_path: "departments.json"
    input_file_type: "json"
    hive_table: "departments"
    hive_database: "test_db"

mappings:
  employees:
    employee_id:
      source: "employee_id"
      target: "emp_id"
      sourceType: "string"
      targetType: "int"
    
    full_name:
      source: "personal_info.name"  # Nested field access
      target: "employee_name"
      sourceType: "string"
      targetType: "string"
    
    email:
      source: "personal_info.email"
      target: "work_email"
      sourceType: "string"
      targetType: "string"
    
    department:
      source: "employment.department"  # Nested field access
      target: "dept_name"
      sourceType: "string"
      targetType: "string"
    
    salary:
      source: "employment.salary"
      target: "annual_salary"
      sourceType: "string"
      targetType: "double"
    
    company:
      source: "employment.company"
      target: "company_name"
      sourceType: "string"
      targetType: "string"
    
    start_date:
      source: "start_date"
      target: "joining_date"
      sourceType: "string"
      targetType: "string"

  departments:
    department_id:
      source: "department_id"
      target: "dept_id"
      sourceType: "string"
      targetType: "int"
    
    department_name:
      source: "department_name"
      target: "dept_name"
      sourceType: "string"
      targetType: "string"

validations:
  employees:
    - type: "value_match"
      description: "Validate key fields match between source and target"
      columns:
        - $ref: "#/mappings/employees"

  departments:
    - type: "value_match"
      description: "Validate key fields match between source and target"
      columns:
        - $ref: "#/mappings/departments"